import requests

url = 'http://127.0.0.1:5000/api?GENDER=M&AGE=19&SMOKING=TRUE&YELLOW_FINGERS=FALSE&ANXIETY=FALSE&PEER_PRESSURE=FALSE&CHRONIC_DISEASE=FALSE&FATIGUE=FALSE&ALLERGY=FALSE&WHEEZING=FALSE&ALCOHOL_CONSUMING=TRUE&COUGHING=FALSE&SHORTNESS_OF_BREATH=FALSE&SWALLOWING_DIFFICULTY=FALSE&CHEST_PAIN=FALSE'

x = requests.get(url)

print(x.json())
